CREATE TABLE IF NOT EXISTS playlists(
	id INTEGER AUTOINCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(1000) DEFAULT NULL,
	image BLOB DEFAULT NULL,
	PRIMARY KEY(id),
);

CREATE TABLE IF NOT EXISTS songs(
	id INTEGER AUTOINCREMENT, 
	name VARCHAR(100), 
	size INT NOT NULL,
	idPlayList ,
	data BLOB NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idPlayList) REFERENCES playlists(id)
        ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS isongs ON songs(name,size);


